gxqpt:
  port:
    nginx: 10086
    eureka: 10030
    gate: ${gxqpt.port.nginx}   # 测试环境使用nginx
  hostname:
    redis: 192.168.1.204      # 根据环境更改
    rabbitmq: 139.159.241.21   # 根据环境更改
    mysql: 58.16.181.23       # 根据环境更改
    nginx: 58.16.181.23       # 测试不走nginx 就填写本机
    eureka: 192.168.1.204     # 根据环境更改
    gate: ${gxqpt.hostname.nginx}     # 测试环境使用nginx
    auth: 192.168.1.204
  mysql:
    admin:
      database: gxqpt_core_test       # 根据环境更改
    port: 3306                  # 根据环境更改
    username: root              # 根据环境更改
    password: LLm65c0VVd3axid9u+Y7DZeKwcODMjU95FRhxom6ApE2yZ1kbi5YzSsdAIz+edUOZH3Engm17+NyfyNczpaYlw==

spring:
  profiles:
    active: test
  redis:
    host: ${gxqpt.hostname.redis}
    port: 6379
    pool:
      max-active: 10
      min-idle: 1
      max-idle: 4
      max-wait: 100
    key-prefix: test
  rabbitmq:
    port: 5672
    username: gxqpt
    password: gxqpt

eureka:
  client:
    serviceUrl:
      defaultZone: http://${gxqpt.hostname.eureka}:${gxqpt.port.eureka}${gxqpt.context-path.eureka}/eureka/

id-generator:
  machine-code: 1  # id生成器机器掩码
