gxqpt:
  port:
    nginx: 10086
    eureka: 10030
    gate: ${gxqpt.port.nginx}  # 正式环境使用nginx
  hostname:
#    redis: 58.16.181.23       # 根据环境更改
#    rabbitmq: 58.16.181.23    # 根据环境更改
    redis: 192.168.30.156      # 根据环境更改
    rabbitmq: 192.168.30.156   # 根据环境更改
    mysql: 192.168.30.156     # 根据环境更改
    nginx: 58.16.248.9      # 测试不走nginx 就填写本机
    eureka: 58.16.248.9     # 根据环境更改
    gate: ${gxqpt.hostname.nginx}      # 正式环境使用nginx
    auth: 192.168.30.152
  mysql:
    admin:
      database: gxqpt_core_prod      # 根据环境更改
      max-active: 10
    port: 3306                  # 根据环境更改
    username: root              # 根据环境更改
    password: LLm65c0VVd3axid9u+Y7DZeKwcODMjU95FRhxom6ApE2yZ1kbi5YzSsdAIz+edUOZH3Engm17+NyfyNczpaYlw==

spring:
  profiles:
    active: prod
  redis:
    key-prefix: prod
    pool:
      max-active: 100
      min-idle: 2
      max-idle: 8
      max-wait: 100
  rabbitmq:
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://${gxqpt.hostname.eureka}:${gxqpt.port.eureka}${gxqpt.context-path.eureka}/eureka/

id-generator:
  machine-code: 1  # id生成器机器掩码
