server:
  port: 9999
  servlet:
      context-path:
spring:
  application:
    name: gate-server
  profiles:
      active: dev
  servlet:
      multipart:
        max-file-size: 512MB
        max-request-size: 512MB     # Max file size，默认1M

zuul:
  ratelimit: # 网关限流
    enabled: false  # 本地启动， 无需验证
  prefix: /api
  routes:
    admin:
      path: /admin/**
      url: http://localhost:10001/
    file:
      path: /file/**
      url: http://localhost:10002/
boke:
  hostname:
    eureka: 127.0.0.1
    gate: 127.0.0.1
  context-path:
    eureka: /boke-eureka
    gate: /api
  port:
    eureka: 8761
    gate: 10002
eureka:
  instance:
      # 是否采用ip
      preferIpAddress: true
      # ip地址
      ip-address: ${boke.hostname.gate}
      # 实例id
      instance-id: ${boke.hostname.gate}:${server.port}${server.servlet.context-path}
  client:
    serviceUrl:
      defaultZone: http://${boke.hostname.eureka}:${boke.port.eureka}${boke.context-path.eureka}/eureka/

gate:
  ignore:
    start-with-list:
      - /admin/user/login
      - /static
#      - /auth/app
#      - /api/admin/p/login
#      - /auth/client
      - /**/swagger-ui.html
      - /**/webjars/**
      - /**/v2/api-docs/**
      - /**/swagger-resources/**
      - /auth/**
      - /mt/userConfi/mtMoveLogin