server:
  port: 9999
spring:
  application:
    name: gate-server
zuul:
  prefix: /api
  routes:
    admin:
      path: /admin/**
      url: http://123.56.221.77:10001/
    file:
      path: /file/**
      url: http://123.56.221.77:10002/
boke:
  hostname:
    eureka: 123.56.221.77
    gate: 123.56.221.77
  context-path:
    eureka: /boke-eureka
    gate: /api
  port:
    eureka: 8761
    gate: 10002
eureka:
  client:
    serviceUrl:
      defaultZone: http://${boke.hostname.eureka}:${boke.port.eureka}${boke.context-path.eureka}/eureka/
gate:
  ignore:
    start-with-list:
      - /admin/user/login
      - /static
#      - /auth/app
#      - /api/admin/p/login
#      - /auth/client
      - /**/swagger-ui.html
      - /**/webjars/**
      - /**/v2/api-docs/**
      - /**/swagger-resources/**
      - /auth/**
      - /mt/userConfi/mtMoveLogin