server:
  port: 10000
  servlet:
      context-path:
spring:
  application:
    name: gate-server
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB     # Max file size，默认1M
zuul:
  prefix: /api
  routes:
    admin:
      path: /admin/**
      url: http://${boke.hostname.gate}:10001/
    file:
      path: /file/**
      url: http://${boke.hostname.gate}:10002/
    python:
      path: /ai/**
      url: http://localhost:10003/
boke:
  hostname:
    eureka: 127.0.0.1
    gate: 127.0.0.1
  context-path:
    eureka: /boke-eureka
    gate: /api
  port:
    eureka: 8761
eureka:
    # 是否采用ip
    preferIpAddress: true
    # ip地址
    ip-address: ${boke.hostname.gate}
    # 实例id
    instance-id: ${boke.hostname.gate}:${server.port}${server.servlet.context-path}
gate:
  ignore:
    start-with-list:
      - /admin/user/login
      - /static
#      - /auth/app
#      - /api/admin/p/login
#      - /auth/client
      - /**/swagger-ui.html
      - /**/webjars/**
      - /**/v2/api-docs/**
      - /**/swagger-resources/**
      - /auth/**
      - /mt/userConfi/mtMoveLogin